services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres_etl:
    image: postgres:latest
    container_name: postgres_etl_db
    restart: always
    environment:
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_password
      POSTGRES_DB: etl_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_etl_data:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.7.3
    container_name: airflow
    restart: always
    depends_on:
      - postgres
      - postgres_etl
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow_db
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__ETL__SQL_ALCHEMY_CONN: postgresql+psycopg2://etl_user:etl_password@postgres_etl/etl_db
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    entrypoint: /bin/bash -c "airflow db init && airflow webserver & airflow scheduler"

volumes:
  postgres_data:
  postgres_etl_data:
  airflow_dags:
  airflow_logs:
  airflow_plugins:
