services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${AIRFLOW_DB_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_DB_PASSWORD}
      POSTGRES_DB: ${AIRFLOW_DB_NAME}
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres_etl:
    image: postgres:latest
    container_name: postgres_etl_db
    restart: always
    environment:
      POSTGRES_USER: ${ETL_DB_USER}
      POSTGRES_PASSWORD: ${ETL_DB_PASSWORD}
      POSTGRES_DB: ${ETL_DB_NAME}
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - ./etl_db/postgres_etl_data:/var/lib/postgresql/data
      - ./etl_db/procedures:/docker-entrypoint-initdb.d
      - ./etl_db/import_files:/data
      - ./etl_db/sql_scripts:/sql_scripts
      - ./shared_data_S3_replacement:/shared:rw
      - ./etl_db/pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: >
      postgres -c hba_file=/etc/postgresql/pg_hba.conf

  airflow-webserver:
    image: apache/airflow:2.7.3-python3.11
    container_name: airflow_webserver
    restart: always
    depends_on:
      - postgres
      - postgres_etl
    environment:
      _AIRFLOW_DB_MIGRATE: 'true'
      DEFAULT_PASSWORD: admin
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
      AIRFLOW__LOG_RETENTION__MAX_LOG_AGE_DAYS: 30
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@${AIRFLOW_DB_HOST}:${AIRFLOW_DB_PORT}/${AIRFLOW_DB_NAME}
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow_src/dags
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_SECRET_KEY}
      PYTHONPATH: /opt/airflow_src:/opt/airflow_src/dags:/opt/airflow_src/lib
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./airflow_src:/opt/airflow_src
      - ./shared_data_S3_replacement:/shared
    entrypoint: >
      /bin/bash -c "airflow db migrate &&
      airflow users create --username $AIRFLOW_USER --password $AIRFLOW_USER_PASSWORD --firstname Admin --lastname User --role Admin --email admin@example.com &&
      exec airflow webserver"
  
  airflow_scheduler:
    image: apache/airflow:2.7.3-python3.11
    container_name: airflow_scheduler
    restart: always
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@${AIRFLOW_DB_HOST}:${AIRFLOW_DB_PORT}/${AIRFLOW_DB_NAME}
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow_src/dags
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_SECRET_KEY}
      PYTHONPATH: /opt/airflow_src:/opt/airflow_src/dags:/opt/airflow_src/lib
    env_file:
      - .env
    volumes:
      - ./airflow_src:/opt/airflow_src
      - ./shared_data_S3_replacement:/shared
    command: >
      bash -c "exec airflow scheduler"

volumes:
  postgres_data:
  postgres_etl_data:
  airflow_dags:
  airflow_logs:
  airflow_plugins: