services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres_etl:
    image: postgres:latest
    container_name: postgres_etl_db
    restart: always
    environment:
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_password
      POSTGRES_DB: etl_db
    ports:
      - "5433:5432"
    volumes:
      - ./etl_db/postgres_etl_data:/var/lib/postgresql/data
      - ./etl_db/procedures:/docker-entrypoint-initdb.d
      - ./etl_db/import_files:/data
      - ./etl_db/sql_scripts:/sql_scripts
      - ./etl_db/run_on_start.sh:/run_on_start.sh
      - ./shared_data_S3_replacement:/shared
    entrypoint:
      ["/bin/bash", "/run_on_start.sh"]

  airflow:
    image: apache/airflow:2.7.3
    container_name: airflow
    restart: always
    depends_on:
      - postgres
      - postgres_etl
    environment:
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: airflow
      _AIRFLOW_WWW_USER_PASSWORD: airflow
      DEFAULT_PASSWORD: admin
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow_db
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      ETL_DB_NAME: etl_db
      ETL_DB_HOST: postgres_etl
      ETL_DB_PORT: 5432
      ETL_DB_USER: etl_user
      ETL_DB_PASSWORD: etl_password
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./shared_data_S3_replacement:/shared
    entrypoint: >
      /bin/bash -c "airflow db migrate &&
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com &&
      airflow webserver & airflow scheduler"
volumes:
  postgres_data:
  postgres_etl_data:
  airflow_dags:
  airflow_logs:
  airflow_plugins: