[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".git",
    ".ruff_cache",
    ".venv",
    "venv",
    "__pypackages__",
    "build",
    "dist",
]

# Same as Black.
line-length = 88

[tool.ruff.lint]
# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
select = ["E", "F"]
# Ignore unused imports globally
ignore = ["F401", "E501"]

[tool.ruff.lint.per-file-ignores]
# Ignore unused imports in `__init__.py` files.
"__init__.py" = ["F401"] 