[tool.ruff]

exclude = [
    ".git",
    ".ruff_cache",
    ".venv",
    "venv",
    "__pypackages__",
    "build",
    "dist",
]


line-length = 88


select = ["E", "F"]

[tool.ruff.per-file-ignores]

"__init__.py" = ["F401"] 